name: Release Tauri App

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux-arm64:
    name: Build Orange Pi Linux ARM64
    runs-on: ubuntu-22.04-arm

    defaults:
      run:
        working-directory: Pigeon

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: Pigeon/package-lock.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libwebkit2gtk-4.1-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            xdg-utils

      - name: Install npm packages
        run: npm ci

      - name: Build Tauri application
        run: npm run tauri build
        env:
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OrangePi-MediaPlayer-linux-arm64
          path: |
            Pigeon/src-tauri/target/release/bundle/deb/*.deb
            Pigeon/src-tauri/target/release/bundle/appimage/*.AppImage


  release:
    name: Create GitHub Release
    needs:
      - build-linux-arm64

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: OrangePi-MediaPlayer-linux-arm64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
            *.AppImage
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}